name: Build and release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: registry.cern.ch
  IMAGE: cern-sis/inspirehep/refextract

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get install poppler-utils

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -e .[docs,tests]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh

      - name: Build package
        if: ${{ success() && github.event_name == 'push' }}
        run: |
          python setup.py sdist bdist_wheel

  push_to_registry_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Image
        id: build
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v6
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE }}
          cache: false
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Deploy QA
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6
        with:
          event-type: update
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}@${{ steps.build.outputs.image-digest }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
